# 伺服器端口配置
server:
  port: 8081  # 用戶服務端口

# Spring 應用程式配置
spring:
  application:
    name: user-service  # 應用程式名稱，用於服務識別
  datasource:
    # H2 內存數據庫配置
    url: jdbc:h2:mem:ecommerce_user
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      # 自動更新資料庫結構，根據實體類生成或更新表結構
      ddl-auto: update
    # 顯示 SQL 語句，方便調試
    show-sql: true
    properties:
      hibernate:
        # 格式化 SQL 輸出，提高可讀性
        format_sql: true
        # 使用 H2 方言
        dialect: org.hibernate.dialect.H2Dialect
  cloud:
    config:
      # 禁用配置中心，在本地開發時方便調試
      # 生產環境應該啟用此功能，從配置中心獲取配置
      enabled: false

# Eureka 客戶端配置
eureka:
  client:
    service-url:
      # Eureka Server 地址，用於註冊自己
      defaultZone: http://localhost:8761/eureka/
    # 暫時禁用服務註冊，避免依賴 Eureka 服務器
    enabled: false
  instance:
    # 優先使用 IP 地址而不是主機名，方便服務間通訊
    prefer-ip-address: true

# JWT 配置
jwt:
  # JWT 密鑰，用於簽名 JWT 令牌
  # 生產環境應使用更複雜的密鑰並妥善保管
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  # JWT 過期時間，單位為毫秒，這裡設置為 24 小時
  expiration: 86400000

# 管理端點配置
management:
  endpoints:
    web:
      exposure:
        # 暴露所有管理端點，用於監控和管理
        include: "*"